### ISSUE TITLE
Return status code when rejecting promise

### ISSUE THREAD

**Issue by Jswk1** [pankleks/planck-http-fetch#3]
```
reject(new Error(`Http fetch failed, status = ${response.statusCode}, ${response.statusMessage}`));
```

Please consider returning the `response.statusCode` as sepeate property when promise is rejected. Sometimes you might need to retry some request when specific status codes are returned (for example error `500` from external API) and currently you have to extract it from the string which is not cool.

**Comment by pankleks** [comment]
now exception thrown has `statusCode` field
